name: Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[tests]
        pip install -U git+https://github.com/bgyori/indra.git@wm_readers
    - name: Run unit tests
      run: |
        export NOSEATTR="!notravis"
        export INDRA_WM_CACHE="."
        export INDRA_WM_SERVICE_DB='sqlite:///:memory:'
        nosetests indra_world -a $NOSEATTR -v --with-coverage --cover-inclusive --cover-package=indra_world
